language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.1.4
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4.6
  - DJANGO_VERSION=1.5.2
matrix:
  exclude:
    - python: "2.5"
      env: "DJANGO_VERSION=1.5.2"
# command to install requirements
install:
 - pip install argparse
 - pip install -q Django==$DJANGO_VERSION --use-mirrors
# command to run tests
script: python quicktest.py greeking
