language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.2.7
  - DJANGO_VERSION=1.3.1
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.4
  - DJANGO_VERSION=1.6.1
# command to install requirements
install:
 - pip install -r requirements.txt
 - pip install -q Django==$DJANGO_VERSION
# command to run tests
script:
  - pep8 greeking
  - pyflakes greeking
  - coverage run quicktest.py greeking
# Report coverage results to coveralls.io
after_success:
 - coveralls
